package migrations

import (
	"database/sql"
	"fmt"

	"github.com/sirupsen/logrus"
)

func Up(db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db not init")
	}

	tx, err := db.Begin()
	if err != nil {
		logrus.Error("migrations.Up: error beginning transaction: ", err)
		return err
	}

	// Проверяем, существует ли тип 'status'
	var typeExists bool
	err = tx.QueryRow(`
        SELECT EXISTS (
            SELECT 1
            FROM pg_type
            WHERE typname = 'status'
        )
    `).Scan(&typeExists)

	if err != nil {
		tx.Rollback()
		logrus.Error("migrations.Up: error checking for type status: ", err)
		return err
	}

	if !typeExists {
		if _, err := tx.Exec(`
			CREATE TYPE status AS ENUM ('FAIL', 'REGISTER', 'BEGIN', 'UPLOAD', 'RECOGNITION', 'WAIT', 'DOWNLOAD', 'SUCCESS');
		`); err != nil {
			tx.Rollback()
			logrus.Error("migrations.Up: error creating type status: ", err)
			return err
		}
		// if _, err := tx.Exec(`
		// 	ALTER TYPE status ADD VALUE 'REGISTER';
		// `); err != nil {
		// 	tx.Rollback()
		// 	logrus.Error("migrations.Up: error adding value REGISTER to type status: ", err)
		// 	return err
		// }
	}

	if _, err := tx.Exec(`
			CREATE TABLE IF NOT EXISTS voice_recognize
			(
				id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				chat_id BIGINT, -- идентификатор чата для ответа пользователю
				voice_data BYTEA, -- бинарные данные аудио
				process_step status, -- используем созданный enum
				request_file_id VARCHAR, -- ответ от ручки upload
				recognize_id VARCHAR, -- ответ от ручки recognize
				response_file_id VARCHAR, -- ответ от ручки status
				transcription TEXT, -- ответ от ручки download (расшифрованный текст)
				summary TEXT,  -- выжимка гигачата
				created_at TIMESTAMP WITH TIME ZONE
			);
		`); err != nil {
		tx.Rollback()
		logrus.Error("migrations.Up: error creating table voice_recognize: ", err)
		return err
	}

	if err = tx.Commit(); err != nil {
		tx.Rollback()
		logrus.Error("migrations.Up: error committing transaction: ", err)
		return err
	}

	logrus.Info("migrations.Up: create table voice_recognize and type status")
	return nil
}

func Down(db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db not init")
	}

	tx, err := db.Begin()
	if err != nil {
		logrus.Error("migrations.Down: error beginning transaction: ", err)
		return err
	}

	if _, err := tx.Exec(`DROP TABLE IF EXISTS voice_recognize;`); err != nil {
		tx.Rollback()
		logrus.Error("migrations.Down: error dropping table voice_recognize: ", err)
		return err
	}

	if _, err := tx.Exec(`DROP TYPE IF EXISTS status CASCADE;`); err != nil {
		tx.Rollback()
		logrus.Error("migrations.Down: error dropping type status: ", err)
		return err
	}

	if err = tx.Commit(); err != nil {
		tx.Rollback()
		logrus.Error("migrations.Down: error committing transaction: ", err)
		return err
	}

	logrus.Info("migrations.Down: drop table voice_recognize and type status")
	return nil
}
