package migrations

import (
	"database/sql"
	"fmt"
)

func Up(db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db not init")
	}

	tx, err := db.Begin()
	if err != nil {
		return err
	}

	// Проверяем, существует ли тип 'status'
	var typeExists bool
	err = tx.QueryRow(`
        SELECT EXISTS (
            SELECT 1
            FROM pg_type
            WHERE typname = 'status'
        )
    `).Scan(&typeExists)

	if err != nil {
		tx.Rollback()
		return err
	}

	if !typeExists {
		if _, err := tx.Exec(`
			CREATE TYPE status AS ENUM ('FAIL', 'BEGIN', 'UPLOAD', 'RECOGNITION', 'WAIT', 'DOWNLOAD', 'SUCCESS');
		`); err != nil {
			tx.Rollback()
			return err
		}
	}

	if _, err := tx.Exec(`
			CREATE TABLE IF NOT EXISTS voice_recognize
			(
				id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				chat_id BIGINT, -- идентификатор чата для ответа пользователю
				voice_data BYTEA, -- бинарные данные аудио
				process_step status, -- используем созданный enum
				request_file_id VARCHAR, -- ответ от ручки upload
				recognize_id VARCHAR, -- ответ от ручки recognize
				response_file_id VARCHAR, -- ответ от ручки status
				transcription TEXT, -- ответ от ручки download (расшифрованный текст)
				summary TEXT,  -- выжимка гигачата
				created_at TIMESTAMP WITH TIME ZONE
			);
		`); err != nil {
		tx.Rollback()
		return err
	}

	if err = tx.Commit(); err != nil {
		tx.Rollback()
		return err
	}

	return nil
}

func Down(db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db not init")
	}

	tx, err := db.Begin()
	if err != nil {
		return err
	}

	if _, err := tx.Exec(`DROP TABLE IF EXISTS voice_recognize;`); err != nil {
		tx.Rollback()
		return err
	}

	if _, err := tx.Exec(`DROP TYPE IF EXISTS status;`); err != nil {
		tx.Rollback()
		return err
	}

	if err = tx.Commit(); err != nil {
		tx.Rollback()
		return err
	}

	return nil
}
